fix backup scripts

diff --git a/roles/odoo-scripts/files/install b/roles/odoo-scripts/files/install
--- a/roles/odoo-scripts/files/install
+++ b/roles/odoo-scripts/files/install
@@ -1,4 +1,10 @@
-#!/bin/sh
+#!/bin/bash
+
+# Exit script if command fails
+# -u stops the script on unset variables
+# -e stops the script on errors
+# -o pipefail stops the script if a pipe fails
+set -e
 
 REPOSITORY=https://raw.githubusercontent.com/mint-system/ansible-playbooks
 
