odoo scripts

diff --git a/roles/odoo-scripts/files/odoo-backup b/roles/odoo-scripts/files/odoo-backup
--- a/roles/odoo-scripts/files/odoo-backup
+++ b/roles/odoo-scripts/files/odoo-backup
@@ -14,14 +14,14 @@ Help() {
   echo
   echo "$SCRIPT"
   echo
-  echo "Description: Backup odoo database."
+  echo "Description: Backup Odoo database."
   echo "Syntax: $SCRIPT [-p|-d|-o|-h|help]"
   echo "Example: $SCRIPT -p secret -d odoo -o /tmp -h https://odoo.example.com"
   echo "options:"
   echo "  -p    Odoo master password. Defaults to \$ODOO_MASTER_PASSWORD env var."
   echo "  -d    Database name."
-  echo "  -o    Output directory with or without name. Defaults to '/var/tmp'"
-  echo "  -h    Odoo host. Defaults to 'http://localhost:8069'"
+  echo "  -o    Output directory with or without name. Defaults to '/var/tmp'."
+  echo "  -h    Odoo host. Defaults to 'http://localhost:8069'."
   echo "  help  Show $SCRIPT manual."
   echo
 }
@@ -35,14 +35,10 @@ fi
 # Process params
 while getopts ":p: :d: :o: :h:" opt; do
   case $opt in
-    h) ODOO_HOST="$OPTARG"
-    ;;
-    p) PASSWORD="$OPTARG"
-    ;;
-    d) DATABASE="$OPTARG"
-    ;;
-    o) OUTPUT="$OPTARG"
-    ;;
+    h) ODOO_HOST="$OPTARG";;
+    p) PASSWORD="$OPTARG";;
+    d) DATABASE="$OPTARG";;
+    o) OUTPUT="$OPTARG";;
     \?) echo "Invalid option -$OPTARG" >&2
     Help
     exit;;
@@ -78,15 +74,17 @@ fi
 # Set file path
 FILEPATH="${DIR}/${FILE}"
 
-echo "Backup database $DATABASE to $FILEPATH"
+echo "Backup database $DATABASE to $FILEPATH ..."
 
 # Request backup with curl
-curl -X POST \
+ESPONSE=$(curl \
   -F "master_pwd=$PASSWORD" \
   -F "name=$DATABASE" \
   -F "backup_format=zip" \
   -o "$FILEPATH" \
-  "$ODOO_HOST/web/database/backup"
+  "$ODOO_HOST/web/database/backup")
+
+echo "$RESPONSE" | grep 'error' && exit 1
 
 # Grep error if is html response
 FILETYPE=$(file --mime-type -b "$FILEPATH")
