add version command to all scripts

diff --git a/roles/odoo_scripts/files/docker-odoo-clear-assets b/roles/odoo_scripts/files/docker-odoo-clear-assets
--- a/roles/odoo_scripts/files/docker-odoo-clear-assets
+++ b/roles/odoo_scripts/files/docker-odoo-clear-assets
@@ -3,6 +3,7 @@ set -e
 
 # Get script name
 SCRIPT=$(basename "$0")
+VERSION="1.0.0"
 
 # Display Help
 Help() {
@@ -10,11 +11,12 @@ Help() {
   echo "$SCRIPT"
   echo
   echo "Description: Clear all assets of Odoo instance."
-  echo "Syntax: $SCRIPT [-c||help]"
+  echo "Syntax: $SCRIPT [-c|-d|-v|help]"
   echo "Example: $SCRIPT -c odoo01 -d erp"
   echo "options:"
   echo "  -c    Docker container. Defaults to 'odoo'."
   echo "  -d    Database name. Defaults to 'odoo'."
+  echo "  -v    Show $SCRIPT version."
   echo "  help  Show $SCRIPT manual."
   echo
 }
@@ -26,16 +28,17 @@ if [[ $1 == 'help' ]]; then
 fi
 
 # Process params
-while getopts ":d: :c:" opt; do
-  case $opt in
-  c) CONTAINER="$OPTARG" ;;
-  d) DATABASE="$OPTARG" ;;
-  \?)
-    echo "Invalid option -$OPTARG" >&2
-    Help
-    exit
-    ;;
-  esac
+while getopts ":c: :d: :v" opt; do
+    case $opt in
+        c) CONTAINER="$OPTARG" ;;
+        d) DATABASE="$OPTARG" ;;
+        v) echo "$SCRIPT version $VERSION"
+        exit 0
+        ;;
+        \?) echo "Invalid option -$OPTARG" >&2
+        Help
+        exit;;
+    esac
 done
 
 # Fallback to environment vars and default values
diff --git a/roles/odoo_scripts/files/docker-odoo-install b/roles/odoo_scripts/files/docker-odoo-install
--- a/roles/odoo_scripts/files/docker-odoo-install
+++ b/roles/odoo_scripts/files/docker-odoo-install
@@ -3,6 +3,7 @@ set -e
 
 # Get script name
 SCRIPT=$(basename "$0")
+VERSION="1.0.0"
 
 # Display Help
 Help() {
@@ -10,13 +11,14 @@ Help() {
     echo "$SCRIPT"
     echo
     echo "Description: Install Odoo database in Docker container."
-    echo "Syntax: $SCRIPT [-d|-m|-c|help]"
+    echo "Syntax: $SCRIPT [-d|-m|-c|-w|-v|help]"
     echo "Example: $SCRIPT -d erp -m hr_timesheet -c odoo01 -w all"
     echo "options:"
     echo "  -d    Database name. Defaults to 'odoo'."
     echo "  -m    List of odoo modules. Defaults to 'base'."
     echo "  -c    Docker container. Defaults to 'odoo'."
     echo "  -w    Without demo data."
+    echo "  -v    Show $SCRIPT version."
     echo "  help  Show $SCRIPT manual."
     echo
 }
@@ -28,16 +30,19 @@ if [[ $1 == 'help' ]]; then
 fi
 
 # Process params
-while getopts ":d: :m: :c: :w:" opt; do
-  case $opt in
-    m) MODULES="$OPTARG";;
-    c) CONTAINER="$OPTARG";;
-    d) DATABASE="$OPTARG";;
-    w) WITHOUT_DEMO="--without-demo=$OPTARG";;
-    \?) echo "Invalid option -$OPTARG" >&2
-    Help
-    exit;;
-  esac
+while getopts ":d: :m: :c: :w: :v" opt; do
+    case $opt in
+        m) MODULES="$OPTARG";;
+        c) CONTAINER="$OPTARG";;
+        d) DATABASE="$OPTARG";;
+        w) WITHOUT_DEMO="--without-demo=$OPTARG";;
+        v) echo "$SCRIPT version $VERSION"
+        exit 0
+        ;;
+        \?) echo "Invalid option -$OPTARG" >&2
+        Help
+        exit;;
+    esac
 done
 
 # Fallback to environment vars and default values
@@ -46,11 +51,11 @@ done
 
 # Install with Docker exec
 if [ "$MODULES" != '' ]; then
-  echo "Install $MODULES for database $DATABASE on container $CONTAINER."
-  docker exec -it $CONTAINER bin/bash -c "odoo -c /etc/odoo/odoo.conf -i $MODULES -d $DATABASE --db_host \$HOST -r \$USER -w \$PASSWORD $WITHOUT_DEMO --stop-after-init --no-http" && docker restart $CONTAINER
+    echo "Install $MODULES for database $DATABASE on container $CONTAINER."
+    docker exec -it $CONTAINER bin/bash -c "odoo -c /etc/odoo/odoo.conf -i $MODULES -d $DATABASE --db_host \$HOST -r \$USER -w \$PASSWORD $WITHOUT_DEMO --stop-after-init --no-http" && docker restart $CONTAINER
 else
-  echo "Init database $DATABASE on container $CONTAINER."
-  docker exec -it $CONTAINER bin/bash -c "odoo -c /etc/odoo/odoo.conf -i base -d $DATABASE --db_host \$HOST -r \$USER -w \$PASSWORD $WITHOUT_DEMO --stop-after-init --no-http" && docker restart $CONTAINER
+    echo "Init database $DATABASE on container $CONTAINER."
+    docker exec -it $CONTAINER bin/bash -c "odoo -c /etc/odoo/odoo.conf -i base -d $DATABASE --db_host \$HOST -r \$USER -w \$PASSWORD $WITHOUT_DEMO --stop-after-init --no-http" && docker restart $CONTAINER
 fi
 
 echo "The Odoo installation for $CONTAINER has finished."
diff --git a/roles/odoo_scripts/files/docker-odoo-list b/roles/odoo_scripts/files/docker-odoo-list
--- a/roles/odoo_scripts/files/docker-odoo-list
+++ b/roles/odoo_scripts/files/docker-odoo-list
@@ -3,6 +3,7 @@ set -e
 
 # Get script name
 SCRIPT=$(basename "$0")
+VERSION="1.0.0"
 
 # Display Help
 Help() {
@@ -10,10 +11,11 @@ Help() {
     echo "$SCRIPT"
     echo
     echo "Description: List all Odoo databases in Docker container."
-    echo "Syntax: $SCRIPT [-c|help]"
+    echo "Syntax: $SCRIPT [-c|-v|help]"
     echo "Example: $SCRIPT -c odoo01"
     echo "options:"
     echo "  -c    Docker container. Defaults to 'odoo'."
+    echo "  -v    Show $SCRIPT version."
     echo "  help  Show $SCRIPT manual."
     echo
 }
@@ -25,13 +27,16 @@ if [[ $1 == 'help' ]]; then
 fi
 
 # Process params
-while getopts ":c:" opt; do
-  case $opt in
-    c) CONTAINER="$OPTARG";;
-    \?) echo "Invalid option -$OPTARG" >&2
-    Help
-    exit;;
-  esac
+while getopts ":c: :v" opt; do
+    case $opt in
+        c) CONTAINER="$OPTARG";;
+        v) echo "$SCRIPT version $VERSION"
+        exit 0
+        ;;
+        \?) echo "Invalid option -$OPTARG" >&2
+        Help
+        exit;;
+    esac
 done
 
 # Fallback to environment vars and default values
diff --git a/roles/odoo_scripts/files/docker-odoo-uninstall b/roles/odoo_scripts/files/docker-odoo-uninstall
--- a/roles/odoo_scripts/files/docker-odoo-uninstall
+++ b/roles/odoo_scripts/files/docker-odoo-uninstall
@@ -3,6 +3,7 @@ set -e
 
 # Get script name
 SCRIPT=$(basename "$0")
+VERSION="1.0.0"
 
 # Display Help
 Help() {
@@ -10,12 +11,13 @@ Help() {
     echo "$SCRIPT"
     echo
     echo "Description: Uninstall Odoo modules in Docker container."
-    echo "Syntax: $SCRIPT [-d|-m|-c|help]"
+    echo "Syntax: $SCRIPT [-c|-d|-u|-v|help]"
     echo "Example: $SCRIPT -d erp -r hr_timesheet -c odoo01"
     echo "options:"
-    echo "  -d    Database name. Defaults to 'odoo'."
-    echo "  -r    Name of Odoo module to uninstall."
     echo "  -c    Docker container. Defaults to 'odoo'."
+    echo "  -d    Database name. Defaults to 'odoo'."
+    echo "  -u    Name of Odoo module to uninstall."
+    echo "  -v    Show $SCRIPT version."
     echo "  help  Show $SCRIPT manual."
     echo
 }
@@ -27,15 +29,18 @@ if [[ $1 == 'help' ]]; then
 fi
 
 # Process params
-while getopts ":d: :r: :c:" opt; do
-  case $opt in
-    r) MODULE="$OPTARG";;
-    c) CONTAINER="$OPTARG";;
-    d) DATABASE="$OPTARG";;
-    \?) echo "Invalid option -$OPTARG" >&2
-    Help
-    exit;;
-  esac
+while getopts ":c: :d: :u: :v" opt; do
+    case $opt in
+        c) CONTAINER="$OPTARG";;
+        d) DATABASE="$OPTARG";;
+        u) MODULE="$OPTARG";;
+        v) echo "$SCRIPT version $VERSION"
+        exit 0
+        ;;
+        \?) echo "Invalid option -$OPTARG" >&2
+        Help
+        exit;;
+    esac
 done
 
 # Fallback to environment vars and default values
diff --git a/roles/odoo_scripts/files/docker-odoo-update b/roles/odoo_scripts/files/docker-odoo-update
--- a/roles/odoo_scripts/files/docker-odoo-update
+++ b/roles/odoo_scripts/files/docker-odoo-update
@@ -3,6 +3,7 @@ set -e
 
 # Get script name
 SCRIPT=$(basename "$0")
+VERSION="1.0.0"
 
 # Display Help
 Help() {
@@ -10,12 +11,13 @@ Help() {
     echo "$SCRIPT"
     echo
     echo "Description: Update Odoo modules in Docker container."
-    echo "Syntax: $SCRIPT [-d|-m|-c|help]"
+    echo "Syntax: $SCRIPT [-c|-d|-u|-v|help]"
     echo "Example: $SCRIPT -d erp -u hr_timesheet -c odoo01"
     echo "options:"
+    echo "  -c    Docker container. Defaults to 'odoo'."
     echo "  -d    Database name. Defaults to 'odoo'."
     echo "  -u    List of odoo modules to update. Defaults to 'all'."
-    echo "  -c    Docker container. Defaults to 'odoo'."
+    echo "  -v    Show $SCRIPT version."
     echo "  help  Show $SCRIPT manual."
     echo
 }
@@ -27,15 +29,18 @@ if [[ $1 == 'help' ]]; then
 fi
 
 # Process params
-while getopts ":d: :u: :c:" opt; do
-  case $opt in
-    u) MODULES="$OPTARG";;
-    c) CONTAINER="$OPTARG";;
-    d) DATABASE="$OPTARG";;
-    \?) echo "Invalid option -$OPTARG" >&2
-    Help
-    exit;;
-  esac
+while getopts ":c: :d: :u: :v" opt; do
+    case $opt in
+        c) CONTAINER="$OPTARG";;
+        d) DATABASE="$OPTARG";;
+        u) MODULES="$OPTARG";;
+        v) echo "$SCRIPT version $VERSION"
+        exit 0
+        ;;
+        \?) echo "Invalid option -$OPTARG" >&2
+        Help
+        exit;;
+    esac
 done
 
 # Fallback to environment vars and default values
diff --git a/roles/odoo_scripts/files/docker-odoo-user b/roles/odoo_scripts/files/docker-odoo-user
--- a/roles/odoo_scripts/files/docker-odoo-user
+++ b/roles/odoo_scripts/files/docker-odoo-user
@@ -3,6 +3,7 @@ set -e
 
 # Get script name
 SCRIPT=$(basename "$0")
+VERSION="1.0.0"
 
 # Display Help
 Help() {
@@ -10,13 +11,14 @@ Help() {
     echo "$SCRIPT"
     echo
     echo "Description: Manage Odoo users."
-    echo "Syntax: $SCRIPT [-d|-c|-a[enable,disable,list,reset]|-i|help]"
+    echo "Syntax: $SCRIPT [-c|-d|-a[enable,disable,list,reset]|-i|-v|help]"
     echo "Example: $SCRIPT -d erp-dev -c odoo06 -a enable -id janikvonrot@mint-system.ch"
     echo "options:"
-    echo "  -d    Database name. Defaults to 'odoo'."
     echo "  -c    Docker container. Defaults to 'odoo'."
+    echo "  -d    Database name. Defaults to 'odoo'."
     echo "  -a    Action to perform. Options: enable, disable, list, reset"
     echo "  -i    User account login id."
+    echo "  -v    Show $SCRIPT version."
     echo "  help  Show $SCRIPT manual."
     echo
 }
@@ -28,16 +30,19 @@ if [[ $1 == 'help' ]]; then
 fi
 
 # Process params
-while getopts ":d:c:a:i:" opt; do
-  case $opt in
-    c) CONTAINER="$OPTARG";;
-    d) DATABASE="$OPTARG";;
-    a) ACTION="$OPTARG";;
-    i) ID="$OPTARG";;
-    \?) echo "Invalid option -$OPTARG" >&2
-    Help
-    exit;;
-  esac
+while getopts ":c: :d: :a: :i: :v" opt; do
+    case $opt in
+        c) CONTAINER="$OPTARG";;
+        d) DATABASE="$OPTARG";;
+        a) ACTION="$OPTARG";;
+        i) ID="$OPTARG";;
+        v) echo "$SCRIPT version $VERSION"
+        exit 0
+        ;;
+        \?) echo "Invalid option -$OPTARG" >&2
+        Help
+        exit;;
+    esac
 done
 
 # Fallback to environment vars and default values
diff --git a/roles/odoo_scripts/files/odoo-backup b/roles/odoo_scripts/files/odoo-backup
--- a/roles/odoo_scripts/files/odoo-backup
+++ b/roles/odoo_scripts/files/odoo-backup
@@ -3,6 +3,7 @@ set -e
 
 # Get script name
 SCRIPT=$(basename "$0")
+VERSION="1.0.0"
 
 # Display Help
 Help() {
@@ -10,13 +11,14 @@ Help() {
   echo "$SCRIPT"
   echo
   echo "Description: Backup Odoo database."
-  echo "Syntax: $SCRIPT [-p|-d|-o|-h|help]"
+  echo "Syntax: $SCRIPT [-p|-d|-o|-h|-v|help]"
   echo "Example: $SCRIPT -p secret -d odoo -o /tmp -h https://odoo.example.com"
   echo "options:"
   echo "  -p    Odoo master password. Defaults to \$ODOO_MASTER_PASSWORD env var."
   echo "  -d    Database name."
   echo "  -o    Output directory with or without filename. Defaults to '/var/tmp'."
   echo "  -h    Odoo host. Defaults to 'http://localhost:8069'."
+  echo "  -v    Show $SCRIPT version."
   echo "  help  Show $SCRIPT manual."
   echo
 }
@@ -28,16 +30,19 @@ if [[ $1 == 'help' ]]; then
 fi
 
 # Process params
-while getopts ":p: :d: :o: :h:" opt; do
-  case $opt in
-    h) ODOO_HOST="$OPTARG";;
-    p) PASSWORD="$OPTARG";;
-    d) DATABASE="$OPTARG";;
-    o) OUTPUT="$OPTARG";;
-    \?) echo "Invalid option -$OPTARG" >&2
-    Help
-    exit;;
-  esac
+while getopts ":p: :d: :o: :h: :v" opt; do
+    case $opt in
+        p) PASSWORD="$OPTARG";;
+        d) DATABASE="$OPTARG";;
+        o) OUTPUT="$OPTARG";;
+        h) ODOO_HOST="$OPTARG";;
+        v) echo "$SCRIPT version $VERSION"
+        exit 0
+        ;;
+        \?) echo "Invalid option -$OPTARG" >&2
+        Help
+        exit;;
+    esac
 done
 
 # Fallback to environment vars and default values
@@ -54,10 +59,10 @@ ODOO_HOST="${ODOO_HOST%/}"
 
 # Check if dir var is file or folder
 if [ "${OUTPUT: -4}" = ".zip" ];then
-  DIR=`dirname "$OUTPUT"`
-  FILE=`basename "$OUTPUT"`
+    DIR=`dirname "$OUTPUT"`
+    FILE=`basename "$OUTPUT"`
 else
-  DIR=$OUTPUT
+    DIR=$OUTPUT
 fi
 
 # Ensure output directory exists
@@ -65,7 +70,7 @@ mkdir -p $DIR
 
 # Ensure file name is set
 if [ -z "$FILE" ];then
-  FILE="$DATABASE.zip"
+    FILE="$DATABASE.zip"
 fi
 
 # Set file path
@@ -75,18 +80,18 @@ echo "Backup database $DATABASE to $FILEPATH ..."
 
 # Request backup with curl
 RESPONSE=$(curl \
-  -F "master_pwd=$PASSWORD" \
-  -F "name=$DATABASE" \
-  -F "backup_format=zip" \
-  -o "$FILEPATH" \
-  "$ODOO_HOST/web/database/backup")
+    -F "master_pwd=$PASSWORD" \
+    -F "name=$DATABASE" \
+    -F "backup_format=zip" \
+    -o "$FILEPATH" \
+    "$ODOO_HOST/web/database/backup")
 
 echo "$RESPONSE" | grep 'error' && exit 1
 
 # Grep error if is html response
 FILETYPE=$(file --mime-type -b "$FILEPATH")
 if [[ "$FILETYPE" == 'text/html' ]]; then
-  grep error "$FILEPATH"
+    grep error "$FILEPATH"
 fi
 
 # Validate zip file
diff --git a/roles/odoo_scripts/files/odoo-drop b/roles/odoo_scripts/files/odoo-drop
--- a/roles/odoo_scripts/files/odoo-drop
+++ b/roles/odoo_scripts/files/odoo-drop
@@ -4,6 +4,7 @@ set -e
 
 # Get script name
 SCRIPT=$(basename "$0")
+VERSION="1.0.0"
 
 # Display Help
 Help() {
@@ -11,12 +12,13 @@ Help() {
   echo "$SCRIPT"
   echo
   echo "Description: Drop Odoo database."
-  echo "Syntax: $SCRIPT [-p|-d|-h|help]"
+  echo "Syntax: $SCRIPT [-p|-d|-h|-v|help]"
   echo "Example: $SCRIPT -p secret -d odoo -h https://odoo.example.org"
   echo "options:"
   echo "  -p    Odoo master password. Defaults to \$ODOO_MASTER_PASSWORD env var and 'admin'."
   echo "  -d    Database name."
   echo "  -h    Odoo host. Defaults to 'http://localhost:8069'."
+  echo "  -v    Show $SCRIPT version."
   echo "  help  Show $SCRIPT manual."
   echo
 }
@@ -28,15 +30,18 @@ if [[ $1 == 'help' ]]; then
 fi
 
 # Process params
-while getopts ":p: :d: :h:" opt; do
-  case $opt in
-    h) ODOO_HOST="$OPTARG";;
-    p) PASSWORD="$OPTARG";;
-    d) DATABASE="$OPTARG";;
-    \?) echo "Invalid option -$OPTARG" >&2
-    Help
-    exit;;
-  esac
+while getopts ":p: :d: :h: :v" opt; do
+    case $opt in
+        p) PASSWORD="$OPTARG";;
+        d) DATABASE="$OPTARG";;
+        h) ODOO_HOST="$OPTARG";;
+        v) echo "$SCRIPT version $VERSION"
+        exit 0
+        ;;
+        \?) echo "Invalid option -$OPTARG" >&2
+        Help
+        exit;;
+    esac
 done
 
 # Fallback to environment vars and default values
@@ -50,16 +55,16 @@ done
 read -p "Please confirm the deletion of $DATABASE on $ODOO_HOST (y/n)? " REPLY
 if [[ $REPLY == y ]]; then
 
-  echo "Deleting Odoo database $DATABASE ..."
+    echo "Deleting Odoo database $DATABASE ..."
 
-  # Request drop with curl
-  RESPONSE=$(curl \
-    -F "master_pwd=${PASSWORD}" \
-    -F "name=${DATABASE}" \
-    "${ODOO_HOST%/}/web/database/drop")
+    # Request drop with curl
+    RESPONSE=$(curl \
+        -F "master_pwd=${PASSWORD}" \
+        -F "name=${DATABASE}" \
+        "${ODOO_HOST%/}/web/database/drop")
 
-  echo "$RESPONSE" | grep 'error' && exit 1
+    echo "$RESPONSE" | grep 'error' && exit 1
 
-  echo "The deletion of Odoo database $DATABASE has finished."
+    echo "The deletion of Odoo database $DATABASE has finished."
 
 fi
diff --git a/roles/odoo_scripts/files/odoo-duplicate b/roles/odoo_scripts/files/odoo-duplicate
--- a/roles/odoo_scripts/files/odoo-duplicate
+++ b/roles/odoo_scripts/files/odoo-duplicate
@@ -4,6 +4,7 @@ set -e
 
 # Get script name
 SCRIPT=$(basename "$0")
+VERSION="1.0.0"
 
 # Display Help
 Help() {
@@ -11,13 +12,14 @@ Help() {
   echo "$SCRIPT"
   echo
   echo "Description: Duplicate Odoo database."
-  echo "Syntax: $SCRIPT [-p|-d|-h|-n|help]"
+  echo "Syntax: $SCRIPT [-p|-d|-h|-n|-v|help]"
   echo "Example: $SCRIPT -p secret -d odoo -h https://odoo.example.org" -n odoo2
   echo "options:"
   echo "  -p    Odoo master password. Defaults to \$ODOO_MASTER_PASSWORD env var and 'admin'."
   echo "  -d    Database name."
   echo "  -h    Odoo host. Defaults to 'http://localhost:8069'."
   echo "  -n    New database name."
+  echo "  -v    Show $SCRIPT version."
   echo "  help  Show $SCRIPT manual."
   echo
 }
@@ -29,16 +31,19 @@ if [[ $1 == 'help' ]]; then
 fi
 
 # Process params
-while getopts ":p: :d: :h: :n:" opt; do
-  case $opt in
-    h) ODOO_HOST="$OPTARG";;
-    p) PASSWORD="$OPTARG";;
-    d) DATABASE="$OPTARG";;
-    n) NEW_DATABASE="$OPTARG";;
-    \?) echo "Invalid option -$OPTARG" >&2
-    Help
-    exit;;
-  esac
+while getopts ":p: :d: :h: :n: :v" opt; do
+    case $opt in
+        p) PASSWORD="$OPTARG";;
+        d) DATABASE="$OPTARG";;
+        n) NEW_DATABASE="$OPTARG";;
+        h) ODOO_HOST="$OPTARG";;
+        v) echo "$SCRIPT version $VERSION"
+        exit 0
+        ;;
+        \?) echo "Invalid option -$OPTARG" >&2
+        Help
+        exit;;
+    esac
 done
 
 # Fallback to environment vars and default values
@@ -54,10 +59,10 @@ echo "Duplicating Odoo database $DATABASE to $NEW_DATABASE ..."
 
 # Request duplication with curl
 RESPONSE=$(curl \
-  -F "master_pwd=${PASSWORD}" \
-  -F "name=${DATABASE}" \
-  -F "new_name=${NEW_DATABASE}" \
-  "${ODOO_HOST%/}/web/database/duplicate")
+    -F "master_pwd=${PASSWORD}" \
+    -F "name=${DATABASE}" \
+    -F "new_name=${NEW_DATABASE}" \
+    "${ODOO_HOST%/}/web/database/duplicate")
 
 echo "$RESPONSE" | grep 'error' && exit 1
 
diff --git a/roles/odoo_scripts/files/odoo-restore b/roles/odoo_scripts/files/odoo-restore
--- a/roles/odoo_scripts/files/odoo-restore
+++ b/roles/odoo_scripts/files/odoo-restore
@@ -3,6 +3,7 @@
 
 # Get script name
 SCRIPT=$(basename "$0")
+VERSION="1.0.0"
 
 # Display Help
 Help() {
@@ -10,7 +11,7 @@ Help() {
   echo "$SCRIPT"
   echo
   echo "Description: Restore Odoo database."
-  echo "Syntax: $SCRIPT [-p|-d|-f|-h|-r|-n|-m|help]"
+  echo "Syntax: $SCRIPT [-p|-d|-f|-h|-r|-n|-m|-v|help]"
   echo "Example: $SCRIPT -p secret -d odoo -f /tmp/odoo.zip -h https://odoo.example.org -n"
   echo "options:"
   echo "  -p    Odoo master password. Defaults to \$ODOO_MASTER_PASSWORD env var and 'admin'."
@@ -19,7 +20,8 @@ Help() {
   echo "  -h    Odoo host. Defaults to 'http://localhost:8069'."
   echo "  -r    Replace existing database."  
   echo "  -n    Neutralize database after restore."  
-  echo "  -m    Database was moved."  
+  echo "  -m    Database was moved."
+  echo "  -v    Show $SCRIPT version."
   echo "  help  Show $SCRIPT manual."
   echo
 }
@@ -36,19 +38,22 @@ NEUTRALIZE="false"
 COPY="true"
 
 # Process params
-while getopts ":r :n :m :p: :d: :f: :h:" opt; do
-  case $opt in
-    r) REPLACE="true";;
-    n) NEUTRALIZE="true";;
-    m) COPY="false";;
-    h) ODOO_HOST="$OPTARG";;
-    p) PASSWORD="$OPTARG";;
-    d) DATABASE="$OPTARG";;
-    f) FILE="$OPTARG";;
-    \?) echo "Invalid option -$OPTARG" >&2
-    Help
-    exit;;
-  esac
+while getopts ":p: :d: :f: :h: :r :n :m :v" opt; do
+    case $opt in
+        p) PASSWORD="$OPTARG";;
+        d) DATABASE="$OPTARG";;
+        f) FILE="$OPTARG";;
+        h) ODOO_HOST="$OPTARG";;
+        r) REPLACE="true";;
+        n) NEUTRALIZE="true";;
+        m) COPY="false";;
+        v) echo "$SCRIPT version $VERSION"
+        exit 0
+        ;;
+        \?) echo "Invalid option -$OPTARG" >&2
+        Help
+        exit;;
+    esac
 done
 
 # Fallback to environment vars and default values
@@ -67,17 +72,17 @@ unzip -q -t $FILE
 
 if $REPLACE; then
   
-  # Ask for confirmation
-  read -p "Please confirm the deletion of $DATABASE on $ODOO_HOST (y/n)? " REPLY
-  if [[ $REPLY == y ]]; then
+    # Ask for confirmation
+    read -p "Please confirm the deletion of $DATABASE on $ODOO_HOST (y/n)? " REPLY
+    if [[ $REPLY == y ]]; then
     echo "Deleting Odoo database $DATABASE ..."
 
     curl \
-      --silent \
-      -F "master_pwd=${PASSWORD}" \
-      -F "name=${DATABASE}" \
-      ${ODOO_HOST%/}/web/database/drop | grep -q -E 'Internal Server Error|Redirecting...'
-  fi
+        --silent \
+        -F "master_pwd=${PASSWORD}" \
+        -F "name=${DATABASE}" \
+        ${ODOO_HOST%/}/web/database/drop | grep -q -E 'Internal Server Error|Redirecting...'
+    fi
 fi
 
 # Start restore
@@ -88,10 +93,10 @@ COMMAND="curl \
 -F \"name=$DATABASE\"
 -F \"backup_file=@$FILE\""
 if $NEUTRALIZE; then
-  COMMAND="$COMMAND -F \"neutralize_database=$NEUTRALIZE\""
+    COMMAND="$COMMAND -F \"neutralize_database=$NEUTRALIZE\""
 fi
 if $COPY; then
-  COMMAND="$COMMAND -F \"copy=$COPY\""
+    COMMAND="$COMMAND -F \"copy=$COPY\""
 fi
 COMMAND="$COMMAND ${ODOO_HOST%/}/web/database/restore"
 
@@ -101,9 +106,9 @@ RESPONSE=$(eval $COMMAND)
 # If redirect is response then restore was succesfull
 CHECK=$(echo "$RESPONSE" | grep -E 'Redirecting...')
 if [[ $CHECK != "" ]]; then
-  echo "The restore for Odoo database $DATABASE has finished."
+    echo "The restore for Odoo database $DATABASE has finished."
 else
-  echo "The restore for Odoo database $DATABASE failed with:"
-  echo "$RESPONSE" | grep error
-  exit 1
+    echo "The restore for Odoo database $DATABASE failed with:"
+    echo "$RESPONSE" | grep error
+    exit 1
 fi
diff --git a/roles/odoo_scripts/files/odoo-user b/roles/odoo_scripts/files/odoo-user
--- a/roles/odoo_scripts/files/odoo-user
+++ b/roles/odoo_scripts/files/odoo-user
@@ -3,6 +3,7 @@ set -e
 
 # Get script name
 SCRIPT=$(basename "$0")
+VERSION="1.0.0"
 
 # Display Help
 Help() {
@@ -10,12 +11,13 @@ Help() {
     echo "$SCRIPT"
     echo
     echo "Description: Manage Odoo users."
-    echo "Syntax: $SCRIPT [-d|-c|-a[enable,disable,list]|-i|help]"
+    echo "Syntax: $SCRIPT [-d|-a[enable,disable,list]|-i|-v|help]"
     echo "Example: $SCRIPT -d erp-dev -a enable -id janikvonrot@mint-system.ch"
     echo "options:"
     echo "  -d    Database name. Defaults to 'odoo'."
     echo "  -a    Action to perform."
     echo "  -i    User account login id."
+    echo "  -v    Show $SCRIPT version."
     echo "  help  Show $SCRIPT manual."
     echo
 }
@@ -27,15 +29,18 @@ if [[ $1 == 'help' ]]; then
 fi
 
 # Process params
-while getopts ":d:c:a:i:" opt; do
-  case $opt in
-    d) PGDATABASE="$OPTARG";;
-    a) ACTION="$OPTARG";;
-    i) ID="$OPTARG";;
-    \?) echo "Invalid option -$OPTARG" >&2
-    Help
-    exit;;
-  esac
+while getopts ":d: :a: :i: :v" opt; do
+    case $opt in
+        d) PGDATABASE="$OPTARG";;
+        a) ACTION="$OPTARG";;
+        i) ID="$OPTARG";;
+        v) echo "$SCRIPT version $VERSION"
+        exit 0
+        ;;
+        \?) echo "Invalid option -$OPTARG" >&2
+        Help
+        exit;;
+    esac
 done
 
 # Fallback to environment vars and default values
