refactor(test-project): remove metabase health check from test script

diff --git a/task b/task
--- a/task
+++ b/task
@@ -563,8 +563,8 @@ test-project() {
         local code=$(curl -o /dev/null -s -w "%{http_code}" -L "http://odoo.local:8080/website/info")
         [[ $code -eq 403 ]] || { echo "http://odoo.local:8080/website/info -> $code"; fail=1; }
 
-        local code=$(curl -o /dev/null -s -w "%{http_code}" -L "http://metabase.local:8080")
-        [[ $code -eq 200 ]] || { echo "http://metabase.local:8080 -> $code"; fail=1; }
+        # local code=$(curl -o /dev/null -s -w "%{http_code}" -L "http://metabase.local:8080")
+        # [[ $code -eq 200 ]] || { echo "http://metabase.local:8080 -> $code"; fail=1; }
 
         local code=$(curl -o /dev/null -s -w "%{http_code}" -L "http://grafana.local:8080")
         [[ $code -eq 200 ]] || { echo "http://grafana.local:8080 -> $code"; fail=1; }
