feat(conventions): add bash coding conventions and update scripts

diff --git a/roles/ansible_scripts/files/ansible-vault-get b/roles/ansible_scripts/files/ansible-vault-get
--- a/roles/ansible_scripts/files/ansible-vault-get
+++ b/roles/ansible_scripts/files/ansible-vault-get
@@ -1,81 +1,82 @@
-#!/bin/bash
+#!/usr/bin/env bash
 set -e
 
 # Get script name
-SCRIPT=$(basename "$0")
-VERSION="1.0.0"
+script=$(basename "$0")
+version="1.0.0"
 
 # Display Help
-Help() {
+help() {
+    local script="$1"
     echo
-    echo "$SCRIPT"
+    echo "$script"
     echo
-    echo "Description: Retrieve secret from Ansible Vault."
-    echo "Syntax: $SCRIPT [-i inventory] [-l host] [-k key] [-V|help]"
-    echo "Example: $SCRIPT -i inventories/odoo -l zeus_erp -k vault_odoo_master_password"
-    echo "options:"
-    echo "  -i    Inventory name."
-    echo "  -l    Ansible hostname."
-    echo "  -k    Vault key variable to grep."
-    echo "  -V    Show $SCRIPT version."
-    echo "  help  Show $SCRIPT manual."
+    echo 'Description: Retrieve secret from Ansible Vault.'
+    echo "Syntax: $script [-i inventory] [-l host] [-k key] [-V|help]"
+    echo "Example: $script -i inventories/odoo -l zeus_erp -k vault_odoo_master_password"
+    echo 'options:'
+    echo '  -i    Inventory name.'
+    echo '  -l    Ansible hostname.'
+    echo '  -k    Vault key variable to grep.'
+    echo '  -V    Show $script version.'
+    echo '  help  Show $script manual.'
     echo
 }
 
 # Show help and exit
 if [[ "$1" == "help" ]]; then
-    Help
+    help "$script"
     exit
 fi
 
 # Process params
 while getopts ":i:l:k:V" opt; do
     case $opt in
-        i) INVENTORY_PATH="$OPTARG";;
-        l) HOST="$OPTARG";;
-        k) VAULT_KEY="$OPTARG";;
-        V) echo "$SCRIPT version $VERSION"
+        i) inventory_path="$OPTARG";;
+        l) host="$OPTARG";;
+        k) vault_key="$OPTARG";;
+        V) echo "$script version $version"
            exit 0
         ;;
         \?) echo "Invalid option -$OPTARG" >&2
-            Help
+            help "$script"
             exit 1
         ;;
     esac
 done
 
-CONFIG_FILE="$HOME/.ansible-vault-get.conf"
+config_file="$HOME/.ansible-vault-get.conf"
 
-if [[ ! -f "$CONFIG_FILE" ]]; then
-    echo "Error: Configuration file '$CONFIG_FILE' not found."
+if [[ ! -f "$config_file" ]]; then
+    echo "Error: Configuration file '$config_file' not found."
     echo "Please init config file with this command:"
-    echo "echo \"ANSIBLE_PATH=/path/to/ansible\" > $CONFIG_FILE"
+    echo "echo \"ANSIBLE_PATH=/path/to/ansible\" > $config_file"
     exit 1
 fi  
 
-[[ -z "$INVENTORY_PATH" ]] && { echo "Parameter -i|inventory path is empty" ; exit 1; }
-[[ -z "$HOST" ]] && { echo "Parameter -l|host is empty" ; exit 1; }
-[[ -z "$VAULT_KEY" ]] && { echo "Parameter -k|key is empty" ; exit 1; }
+[[ -z "$inventory_path" ]] && { echo "Parameter -i|inventory path is empty" ; exit 1; }
+[[ -z "$host" ]] && { echo "Parameter -l|host is empty" ; exit 1; }
+[[ -z "$vault_key" ]] && { echo "Parameter -k|key is empty" ; exit 1; }
 
 
 # Load the inventory path from the configuration file
-ANSIBLE_PATH=$(grep "ANSIBLE_PATH" "$CONFIG_FILE" | cut -d '=' -f2)
+ansible_path=$(grep "ANSIBLE_PATH" "$config_file" | cut -d '=' -f2)
 
-if [[ -z "$ANSIBLE_PATH" ]]; then
-    echo "Error: Ansible path $ANSIBLE_PATH not found."
+if [[ -z "$ansible_path" ]]; then
+    echo "Error: Ansible path $ansible_path not found."
     echo "Update config file with this command:"
-    echo "vi $CONFIG_FILE"
+    echo "vi $config_file"
     exit 1
 fi
 
-cd "$ANSIBLE_PATH"
+cd "$ansible_path"
 source ./task source >/dev/null
 
-VAULT_FILE="$INVENTORY_PATH/host_vars/$HOST/vault.yml"
+vault_file="$inventory_path/host_vars/$host/vault.yml"
 
-if [[ ! -f "$VAULT_FILE" ]]; then
-    echo "Error: Vault file '$VAULT_FILE' not found."
+if [[ ! -f "$vault_file" ]]; then
+    echo "Error: Vault file '$vault_file' not found."
     exit 1
 fi
 
-echo $(ansible-vault view "$VAULT_FILE" | grep "${VAULT_KEY}:" | cut -d ':' -f2)
+echo $(ansible-vault view "$vault_file" | grep "${vault_key}:" | cut -d ':' -f2)
