chore(docker): update docker and postgres role

diff --git a/roles/postgres/files/docker-postgres-list b/roles/postgres/files/docker-postgres-list
--- a/roles/postgres/files/docker-postgres-list
+++ b/roles/postgres/files/docker-postgres-list
@@ -1,40 +1,39 @@
-#!/bin/bash
+#!/usr/bin/env bash
 set -e
 
-# Get script name
-SCRIPT=$(basename "$0")
+script=$(basename "$0")
+version="1.0.1"
 
-# Display Help
-Help() {
+help() {
     echo
-    echo "$SCRIPT"
+    echo "$script"
     echo
-    echo "Description: List all databases in Postgres Docker container."
-    echo "Syntax: $SCRIPT [-c|help]"
-    echo "Example: $SCRIPT -c postgres01"
-    echo "options:"
+    echo 'Description: List all databases in Postgres Docker container.'
+    echo "Syntax: $script [-c|help]"
+    echo 'Example: $script -c postgres01'
+    echo 'options:'
     echo "  -c    Docker container. Defaults to 'postgres'."
-    echo "  help  Show $SCRIPT manual."
+    echo "  help  Show $script manual."
     echo
 }
 
-# Show help and exit
-if [[ "$1" == "help" ]]; then
-    Help
-    exit
+if [[ "$1" == 'help' ]]; then
+    help
+    exit 0
 fi
 
-# Process params
+container='postgres'
 while getopts ":c:" opt; do
   case $opt in
-    c) CONTAINER="$OPTARG";;
-    \?) echo "Invalid option -$OPTARG" >&2
-    Help
-    exit;;
+    c) container="$OPTARG";;
+    \?) echo "Invalid option -$OPTARG" >&2; help; exit 1;;
   esac
 done
 
-# Fallback to environment vars and default values
-: ${CONTAINER:='postgres'}
+[[ -z "$container" ]] && { echo 'Container name is required'; exit 1; }
 
-docker exec "$CONTAINER" /bin/bash -c "psql postgresql://\$POSTGRES_USER:\$POSTGRES_PASSWORD@\$HOSTNAME:5432/postgres -tAc 'SELECT datname FROM pg_database;'"
+docker exec \
+  --env PGPASSWORD="$(docker exec "$container" printenv POSTGRES_PASSWORD)" \
+  "$container" \
+  psql -U "$(docker exec "$container" printenv POSTGRES_USER)" \
+  -h localhost -p 5432 -d postgres -tAc "SELECT datname FROM pg_database WHERE datistemplate = false AND datname NOT IN ('postgres', 'template0', 'template1');"
