backup odoo sites

diff --git a/roles/restic-client/files/odoo-backup b/roles/restic-client/files/odoo-backup
--- a/roles/restic-client/files/odoo-backup
+++ b/roles/restic-client/files/odoo-backup
@@ -1,5 +1,8 @@
 #!/bin/bash
 
+# Exit script if command fails
+set -e
+
 # Display Help
 Help() {
     echo
@@ -7,16 +10,18 @@ Help() {
     echo "###########"
     echo
     echo "Description: Backup odoo database."
-    echo "Syntax: odoo-backup [-p|d|o|h]"
+    echo "Syntax: odoo-backup [-p|-d|-o|-h|help]"
     echo "Example: odoo-backup -p secret -d odoo -o /tmp -h https://odoo.example.com"
     echo "options:"
     echo "  -p    Odoo master password. Defaults to \$ODOO_MASTER_PASSWORD env var."
     echo "  -d    Database name."
     echo "  -o    Output directory. Defaults to '/var/tmp'"
     echo "  -h    Odoo host. Defaults to 'http://localhost:8069'"
+    echo "  help  Show odoo-backup manual."
     echo
 }
 
+# Show help and exit
 if [[ $1 == 'help' ]]; then
     Help
     exit
@@ -39,7 +44,7 @@ while getopts ":p:d:o:h:help:" opt; do
   esac
 done
 
-# Fallback to environment variables
+# Fallback to environment vars and default values
 : ${PASSWORD:=${ODOO_MASTER_PASSWORD}}
 : ${DIR:='/var/tmp'}
 : ${HOST:='http://localhost:8069'}
@@ -50,7 +55,7 @@ done
 [[ -z "$DIR" ]] && { echo "Parameter -d|dir is empty" ; exit 1; }
 [[ -z "$HOST" ]] && { echo "Parameter -h|host is empty" ; exit 1; }
 
-# Create backup
+# Request backup with curl
 curl -X POST \
     -F "master_pwd=${PASSWORD}" \
     -F "name=${DATABASE}" \
@@ -58,7 +63,8 @@ curl -X POST \
     -o ${DIR}/${DATABASE}.zip \
     ${HOST}/web/database/backup
 
+# Validate zip file
+unzip -t "${DIR}/${DATABASE}.zip"
+
 # Notify if backup has finished
-if [[ $? -eq 0 ]]; then
-    echo "The Odoo backup has finished: ${DIR}/${DATABASE}.zip"
-fi
+echo "The Odoo backup has finished: ${DIR}/${DATABASE}.zip"
