feat(mysql): add replace flag to restore script and standardize indentation
- Added -r flag to docker-mysql-restore to replace existing database (drop + recreate)
- Updated docker-mysql-restore to ensure database exists before restoring
- Standardized indentation across all MySQL docker scripts (backup, drop, list, restore)
- Fixed missing newline at end of docker-mysql-restore file
- Updated help documentation to reflect new -r flag and options
- Maintained existing restore behavior for non-replace operations

diff --git a/roles/mysql/files/docker-mysql-backup b/roles/mysql/files/docker-mysql-backup
--- a/roles/mysql/files/docker-mysql-backup
+++ b/roles/mysql/files/docker-mysql-backup
@@ -5,19 +5,19 @@ script=$(basename "$0")
 version="1.0.1"
 
 help() {
-  echo
-  echo "$script"
-  echo
-  echo 'Description: Backup MySQL/MariaDB Docker database.'
-  echo "Syntax: $script [-d|-o|-c|help]"
-  echo 'Example: $script -d mysql,moodle -o /tmp -c mysql01'
-  echo 'options:'
-  echo '  -d    Comma-separated list of database names.'
-  echo '  -a    Backup all databases'
-  echo '  -o    Output directory. Defaults to '\''/var/tmp'\''.'
-  echo '  -c    Docker container name. Defaults to '\''mysql'\''.'
-  echo "  help  Show $script manual."
-  echo
+    echo
+    echo "$script"
+    echo
+    echo 'Description: Backup MySQL/MariaDB Docker database.'
+    echo "Syntax: $script [-d|-o|-c|help]"
+    echo "Example: $script -d mysql,moodle -o /tmp -c mysql01"
+    echo 'options:'
+    echo '  -d    Comma-separated list of database names.'
+    echo '  -a    Backup all databases'
+    echo '  -o    Output directory. Defaults to '\''/var/tmp'\''.'
+    echo '  -c    Docker container name. Defaults to '\''mysql'\''.'
+    echo "  help  Show $script manual."
+    echo
 }
 
 if [[ "$1" == 'help' ]]; then
@@ -30,19 +30,19 @@ dir=/var/tmp
 container=mysql
 
 while getopts ':a :c: :d: :o:' opt; do
-  case $opt in
-    a) all='true'
-    ;;
-    c) container="$OPTARG"
-    ;;
-    d) databases="$OPTARG"
-    ;;
-    o) dir="$OPTARG"
-    ;;
-    \?) echo "Invalid option -$OPTARG" >&2
-    help
-    exit 1;;
-  esac
+    case $opt in
+        a) all='true'
+        ;;
+        c) container="$OPTARG"
+        ;;
+        d) databases="$OPTARG"
+        ;;
+        o) dir="$OPTARG"
+        ;;
+        \?) echo "Invalid option -$OPTARG" >&2
+        help
+        exit 1;;
+    esac
 done
 
 [[ -z "$databases" ]] && [[ -z "$all" ]] && { echo 'Parameter -d or -a|databases or all must be set' ; exit 1; }
@@ -50,16 +50,16 @@ done
 image=$(docker inspect $container --format='{{.Config.Image}}')
 
 if $all; then
-  if [[ "$image" =~ 'mariadb' ]]; then
-    database_list=($(docker exec $container /bin/bash -c "mysql -u \$MARIADB_USER --password=\$MARIADB_PASSWORD \
+    if [[ "$image" =~ 'mariadb' ]]; then
+        database_list=($(docker exec $container /bin/bash -c "mysql -u \$MARIADB_USER --password=\$MARIADB_PASSWORD \
       -Bse 'SHOW DATABASES' | grep -v -E '^(sys|information_schema|mysql|performance_schema)$'"))
-  fi
-  if [[ "$image" =~ 'mysql' ]]; then
-    database_list=($(docker exec $container /bin/bash -c "mysql -p\$MYSQL_ROOT_PASSWORD \
+    fi
+    if [[ "$image" =~ 'mysql' ]]; then
+        database_list=($(docker exec $container /bin/bash -c "mysql -p\$MYSQL_ROOT_PASSWORD \
       -Bse 'SHOW DATABASES' | grep -v -E '^(sys|information_schema|mysql|performance_schema)$'"))
-  fi
-  printf -v databases '%s,' "${database_list[@]}"
-  databases="${databases%,}"
+    fi
+    printf -v databases '%s,' "${database_list[@]}"
+    databases="${databases%,}"
 fi
 
 if [[ -n $databases ]] ; then
@@ -72,18 +72,18 @@ rm -rf "${dir:?}/${container}"/*
 
 for database in "${database_list[@]}"
 do
-  if [[ "$image" =~ 'mariadb' ]]; then
-    echo "Run Docker MariaDB backup for $database"
-    rm -f "${dir}/${container}/${database}.sql"
-    docker exec $container /bin/bash -c "mysqldump -u \$MARIADB_USER --password=\$MARIADB_PASSWORD \
-        $database" > "${dir}/${container}/${database}.sql"
-  fi
-  if [[ "$image" =~ 'mysql' ]]; then
-    echo "Run Docker MySQL backup for $database"
-    rm -f "${dir}/${container}/${database}.sql"
-    docker exec $container /bin/bash -c "mysqldump -p\$MYSQL_ROOT_PASSWORD \
-        $database" > "${dir}/${container}/${database}.sql"
-  fi
+    if [[ "$image" =~ 'mariadb' ]]; then
+        echo "Run Docker MariaDB backup for $database"
+        rm -f "${dir}/${container}/${database}.sql"
+        docker exec $container /bin/bash -c "mysqldump -u \$MARIADB_USER --password=\$MARIADB_PASSWORD \
+            $database" > "${dir}/${container}/${database}.sql"
+    fi
+    if [[ "$image" =~ 'mysql' ]]; then
+        echo "Run Docker MySQL backup for $database"
+        rm -f "${dir}/${container}/${database}.sql"
+        docker exec $container /bin/bash -c "mysqldump -p\$MYSQL_ROOT_PASSWORD \
+            $database" > "${dir}/${container}/${database}.sql"
+    fi
 done
 
 echo "The Docker mysql backup has finished: ${dir}/${container}/{$databases}.sql"
diff --git a/roles/mysql/files/docker-mysql-drop b/roles/mysql/files/docker-mysql-drop
--- a/roles/mysql/files/docker-mysql-drop
+++ b/roles/mysql/files/docker-mysql-drop
@@ -5,17 +5,17 @@ script=$(basename "$0")
 version="1.0.1"
 
 help() {
-  echo
-  echo "$script"
-  echo
-  echo 'Description: Drop MySQL/MariaDB Docker database.'
-  echo "Syntax: $script [-d|-f|-c|help]"
-  echo 'Example: $script -d moodle -c mqysl01'
-  echo 'options:'
-  echo "  -d    Name of database. Defaults to filename"
-  echo "  -c    Docker container name. Defaults to 'mysql'."
-  echo "  help  Show $script manual."
-  echo
+    echo
+    echo "$script"
+    echo
+    echo 'Description: Drop MySQL/MariaDB Docker database.'
+    echo "Syntax: $script [-d|-f|-c|help]"
+    echo "Example: $script -d moodle -c mqysl01"
+    echo 'options:'
+    echo "  -d    Name of database. Defaults to filename"
+    echo "  -c    Docker container name. Defaults to 'mysql'."
+    echo "  help  Show $script manual."
+    echo
 }
 
 if [[ "$1" == 'help' ]]; then
@@ -26,25 +26,25 @@ fi
 container='mysql'
 
 while getopts ":c: :d:" opt; do
-  case $opt in
-    c) container="$OPTARG";;
-    d) database="$OPTARG";;
-    \?) echo "Invalid option -$OPTARG" >&2
-    help
-    exit 1;;
-  esac
+    case $opt in
+        c) container="$OPTARG";;
+        d) database="$OPTARG";;
+        \?) echo "Invalid option -$OPTARG" >&2
+        help
+        exit 1;;
+    esac
 done
 
 [[ -z "$database" ]] && { echo 'Parameter -d|database is empty.' ; exit 1; }
 
 image=$(docker inspect "$container" --format='{{.Config.Image}}')
 if [[ "$image" =~ 'mariadb' ]]; then
-  echo "Drop MariaDB database $database on container $container ..."
-  docker exec "$container" /bin/bash -c "export MYSQL_PWD=\$MARIADB_ROOT_PASSWORD; mysql -N -h\$HOSTNAME -uroot -e 'DROP DATABASE $database;'"
+    echo "Drop MariaDB database $database on container $container ..."
+    docker exec "$container" /bin/bash -c "export MYSQL_PWD=\$MARIADB_ROOT_PASSWORD; mysql -N -h\$HOSTNAME -uroot -e 'DROP DATABASE $database;'"
 fi
 if [[ "$image" =~ 'mysql' ]]; then
-  echo "Drop MySQL database $database on container $container ..."
-  docker exec "$container" /bin/bash -c "export MYSQL_PWD=\$MYSQL_ROOT_PASSWORD; mysql -N -h\$HOSTNAME -uroot -e 'DROP DATABASE $database;'"
+    echo "Drop MySQL database $database on container $container ..."
+    docker exec "$container" /bin/bash -c "export MYSQL_PWD=\$MYSQL_ROOT_PASSWORD; mysql -N -h\$HOSTNAME -uroot -e 'DROP DATABASE $database;'"
 fi
 
 echo 'The Docker MySQL/MariaDB database has been dropped.'
diff --git a/roles/mysql/files/docker-mysql-list b/roles/mysql/files/docker-mysql-list
--- a/roles/mysql/files/docker-mysql-list
+++ b/roles/mysql/files/docker-mysql-list
@@ -25,12 +25,12 @@ fi
 container='mysql'
 
 while getopts ":c:" opt; do
-  case $opt in
-    c) container="$OPTARG";;
-    \?) echo "Invalid option -$OPTARG" >&2
-    help
-    exit 1;;
-  esac
+    case $opt in
+        c) container="$OPTARG";;
+        \?) echo "Invalid option -$OPTARG" >&2
+        help
+        exit 1;;
+    esac
 done
 
 image=$(docker inspect "$container" --format='{{.Config.Image}}')
diff --git a/roles/mysql/files/docker-mysql-restore b/roles/mysql/files/docker-mysql-restore
--- a/roles/mysql/files/docker-mysql-restore
+++ b/roles/mysql/files/docker-mysql-restore
@@ -5,39 +5,39 @@ script=$(basename "$0")
 version="1.0.1"
 
 help() {
-  echo
-  echo "$script"
-  echo
-  echo 'Description: Restore MySQL/MariaDB Docker database.'
-  echo "Syntax: $script [-c|-d|-f|-i|help]"
-  echo 'Example: $script -c mqysl01 -d moodle -f /tmp/dump.sql'
-  echo 'options:'
-  echo '  -c    Docker container name. Defaults to '\''mysql'\''.'
-  echo '  -d    Name of database. Defaults to filename'
-  echo '  -f    Path to sql dump.'
-  echo '  -i    Create database.'
-  echo "  help  Show $script manual."
-  echo
+    echo
+    echo "$script"
+    echo
+    echo 'Description: Restore MySQL/MariaDB Docker database.'
+    echo "Syntax: $script [-c|-d|-f|-r|help]"
+    echo "Example: $script -c mqysl01 -d moodle -f /tmp/dump.sql -r"
+    echo 'options:'
+    echo '  -c    Docker container name. Defaults to '\''mysql'\''.'
+    echo '  -d    Name of database. Defaults to filename'
+    echo '  -f    Path to sql dump.'
+    echo '  -r    Replace existing database (drop + recreate).'
+    echo "  help  Show $script manual."
+    echo
 }
 
 if [[ "$1" == 'help' ]]; then
-    help
-    exit
+  help
+  exit
 fi
 
-create='false'
+replace='false'
 container=mysql
 
-while getopts ':c: :d: :f: :i' opt; do
-  case $opt in
-    c) container="$OPTARG";;
-    d) database="$OPTARG";;
-    f) file="$OPTARG";;
-    i) create='true';;
-    \?) echo "Invalid option -$OPTARG" >&2
-    help
-    exit 1;;
-  esac
+while getopts ':c: :d: :f: :r' opt; do
+    case $opt in
+        c) container="$OPTARG";;
+        d) database="$OPTARG";;
+        f) file="$OPTARG";;
+        r) replace='true';;
+        \?) echo "Invalid option -$OPTARG" >&2
+        help
+        exit 1;;
+    esac
 done
 
 filename=$(basename -- "$file")
@@ -47,24 +47,33 @@ database=${database:="${filename%%.*}"}
 
 image=$(docker inspect $container --format='{{.Config.Image}}')
 
-if $create; then
+if $replace; then
     if [[ "$image" =~ 'mariadb' ]]; then
-        echo "Create MariaDB database $database ..."
-        echo "CREATE DATABASE $database" | docker exec -i "$container" /bin/bash -c "mysql -p\$MARIADB_ROOT_PASSWORD"
+        echo "Drop existing MariaDB database $database..."
+        echo "DROP DATABASE IF EXISTS $database" | docker exec -i "$container" /bin/bash -c "mariadb -p\$MARIADB_ROOT_PASSWORD"
     fi
     if [[ "$image" =~ 'mysql' ]]; then
-        echo "Create MySQL database $database ..."
-        echo "CREATE DATABASE $database" | docker exec -i "$container" /bin/bash -c "mysql -p\$MYSQL_ROOT_PASSWORD"
+        echo "Drop existing MySQL database $database..."
+        echo "DROP DATABASE IF EXISTS $database" | docker exec -i "$container" /bin/bash -c "mysql -p\$MYSQL_ROOT_PASSWORD"
     fi
 fi
 
 if [[ "$image" =~ 'mariadb' ]]; then
-  echo "Restore MariaDB database $database from $file ..."
-  cat "$file" | docker exec -i "$container" /bin/bash -c "mysql -u \$MARIADB_USER --password=\$MARIADB_PASSWORD --force $database"
+    echo "Create MariaDB database $database..."
+    echo "CREATE DATABASE IF NOT EXISTS $database" | docker exec -i "$container" /bin/bash -c "mariadb -p\$MARIADB_ROOT_PASSWORD"
 fi
 if [[ "$image" =~ 'mysql' ]]; then
-  echo "Restore MySQL database $database from $file ..."
-  cat "$file" | docker exec -i "$container" /bin/bash -c "mysql -p\$MYSQL_ROOT_PASSWORD $database"
+    echo "Create MySQL database $database..."
+    echo "CREATE DATABASE IF NOT EXISTS $database" | docker exec -i "$container" /bin/bash -c "mysql -p\$MYSQL_ROOT_PASSWORD"
+fi
+
+if [[ "$image" =~ 'mariadb' ]]; then
+    echo "Restore MariaDB database $database from $file ..."
+    cat "$file" | docker exec -i "$container" /bin/bash -c "mariadb -u root --password=\$MARIADB_ROOT_PASSWORD $database"
+fi
+if [[ "$image" =~ 'mysql' ]]; then
+    echo "Restore MySQL database $database from $file ..."
+    cat "$file" | docker exec -i "$container" /bin/bash -c "mysql -p\$MYSQL_ROOT_PASSWORD $database"
 fi
 
 echo 'The Docker MySQL/MariaDB restore has finished.'
